# Generated by Django 4.2.3 on 2023-09-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduwell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='path',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
